In [3]:
import sklearn as sk
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.metrics import confusion_matrix
from sklearn import svm

In [5]:
x = pd.read_csv('cfs_subset_train.csv')
y = pd.read_csv('cfs_subset_test.csv')
x["protocol_type"] = x["protocol_type"].astype('category')
x["protocol_type"] = x["protocol_type"].cat.codes
x["service"] = x["service"].astype('category')
x["service"] = x["service"].cat.codes
x["flag"] = x["flag"].astype('category')
x["flag"] = x["flag"].cat.codes
y["protocol_type"] = y["protocol_type"].astype('category')
y["protocol_type"] = y["protocol_type"].cat.codes
y["service"] = y["service"].astype('category')
y["service"] = y["service"].cat.codes
y["flag"] = y["flag"].astype('category')
y["flag"] = y["flag"].cat.codes
x_train = x.iloc[: , :8]
y_train = x.iloc[:, 9:]
x_test = y.iloc[: , :8]
y_test = y.iloc[:, 9:]
clf = svm.SVC(C=0.1).fit(x_train, y_train)
preds = clf.predict(x_test)
print(f"Train Accuracy: {clf.score(x_train, y_train)}")
print(f"Test Accuracy: {clf.score(x_test, y_test)}")
print('Confusion Matrix: \n', confusion_matrix(y_test, preds))

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Train Accuracy: 0.9995981608129516
Test Accuracy: 0.22120903011756463
Confusion Matrix: 
 [[21440     0     0]
 [19426    29     0]
 [45376 10782     0]]


In [6]:
x = pd.read_csv('correlation_based_train.csv')
y = pd.read_csv('correlation_based_test.csv')
x["protocol_type"] = x["protocol_type"].astype('category')
x["protocol_type"] = x["protocol_type"].cat.codes
x["service"] = x["service"].astype('category')
x["service"] = x["service"].cat.codes
x["flag"] = x["flag"].astype('category')
x["flag"] = x["flag"].cat.codes
y["protocol_type"] = y["protocol_type"].astype('category')
y["protocol_type"] = y["protocol_type"].cat.codes
y["service"] = y["service"].astype('category')
y["service"] = y["service"].cat.codes
y["flag"] = y["flag"].astype('category')
y["flag"] = y["flag"].cat.codes
x_train = x.iloc[: , :26]
y_train = x.iloc[:, 27:]
x_test = y.iloc[: , :26]
y_test = y.iloc[:, 27:]
clf = svm.SVC().fit(x_train, y_train)
preds = clf.predict(x_test)
print(f"Train Accuracy: {clf.score(x_train, y_train)}")
print(f"Test Accuracy: {clf.score(x_test, y_test)}")
print('Confusion Matrix: \n', confusion_matrix(y_test, preds))

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Train Accuracy: 0.9996754375796917
Test Accuracy: 0.22123994106313044
Confusion Matrix: 
 [[21440     0     0]
 [19423    32     0]
 [45423 10735     0]]


In [7]:
x = pd.read_csv('gain_ratio_train.csv')
y = pd.read_csv('gain_ratio_test.csv')
x["protocol_type"] = x["protocol_type"].astype('category')
x["protocol_type"] = x["protocol_type"].cat.codes
x["service"] = x["service"].astype('category')
x["service"] = x["service"].cat.codes
x["flag"] = x["flag"].astype('category')
x["flag"] = x["flag"].cat.codes
y["protocol_type"] = y["protocol_type"].astype('category')
y["protocol_type"] = y["protocol_type"].cat.codes
y["service"] = y["service"].astype('category')
y["service"] = y["service"].cat.codes
y["flag"] = y["flag"].astype('category')
y["flag"] = y["flag"].cat.codes
x_train = x.iloc[: , :25]
y_train = x.iloc[:, 26:]
x_test = y.iloc[: , :25]
y_test = y.iloc[:, 26:]
clf = svm.SVC().fit(x_train, y_train)
preds = clf.predict(x_test)
print(f"Train Accuracy: {clf.score(x_train, y_train)}")
print(f"Test Accuracy: {clf.score(x_test, y_test)}")
print('Confusion Matrix: \n', confusion_matrix(y_test, preds))

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Train Accuracy: 0.9996574063341189
Test Accuracy: 0.22127085200869628
Confusion Matrix: 
 [[21440     0     0]
 [19420    35     0]
 [45330 10828     0]]


In [8]:
x = pd.read_csv('information_gain_train.csv')
y = pd.read_csv('information_gain_test.csv')
x["protocol_type"] = x["protocol_type"].astype('category')
x["protocol_type"] = x["protocol_type"].cat.codes
x["service"] = x["service"].astype('category')
x["service"] = x["service"].cat.codes
x["flag"] = x["flag"].astype('category')
x["flag"] = x["flag"].cat.codes
y["protocol_type"] = y["protocol_type"].astype('category')
y["protocol_type"] = y["protocol_type"].cat.codes
y["service"] = y["service"].astype('category')
y["service"] = y["service"].cat.codes
y["flag"] = y["flag"].astype('category')
y["flag"] = y["flag"].cat.codes
x_train = x.iloc[: , :26]
y_train = x.iloc[:, 27:]
x_test = y.iloc[: , :26]
y_test = y.iloc[:, 27:]
clf = svm.SVC().fit(x_train, y_train)
preds = clf.predict(x_test)
print(f"Train Accuracy: {clf.score(x_train, y_train)}")
print(f"Test Accuracy: {clf.score(x_test, y_test)}")
print('Confusion Matrix: \n', confusion_matrix(y_test, preds))

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Train Accuracy: 0.9996574063341189
Test Accuracy: 0.22127085200869628
Confusion Matrix: 
 [[21440     0     0]
 [19420    35     0]
 [45330 10828     0]]
