In [2]:
import sklearn as sk
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.metrics import confusion_matrix

In [ ]:
x = pd.read_csv('cfs_subset_train.csv')
y = pd.read_csv('cfs_subset_test.csv')
x["protocol_type"] = x["protocol_type"].astype('category')
x["protocol_type"] = x["protocol_type"].cat.codes
x["service"] = x["service"].astype('category')
x["service"] = x["service"].cat.codes
x["flag"] = x["flag"].astype('category')
x["flag"] = x["flag"].cat.codes
y["protocol_type"] = y["protocol_type"].astype('category')
y["protocol_type"] = y["protocol_type"].cat.codes
y["service"] = y["service"].astype('category')
y["service"] = y["service"].cat.codes
y["flag"] = y["flag"].astype('category')
y["flag"] = y["flag"].cat.codes
x_train = x.iloc[: , :8]
y_train = x.iloc[:, 9:]
x_test = y.iloc[: , :8]
y_test = y.iloc[:, 9:]
rfc = RandomForestClassifier(max_depth=2, random_state=5)
rfc.fit(x_train, y_train)
preds = rfc.predict(x_test)
print(f"Train Accuracy: {rfc.score(x_train, y_train)}")
print(f"Test Accuracy: {rfc.score(x_test, y_test)}")
print('Confusion Matrix: \n', confusion_matrix(y_test, preds))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:20: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().


Train Accuracy: 1.0
Test Accuracy: 0.986759811649305
Confusion Matrix: 
 [[21414    26     0]
 [ 1255 18200     0]
 [    0     4 56154]]


In [ ]:
x = pd.read_csv('correlation_based_train.csv')
y = pd.read_csv('correlation_based_test.csv')
x["protocol_type"] = x["protocol_type"].astype('category')
x["protocol_type"] = x["protocol_type"].cat.codes
x["service"] = x["service"].astype('category')
x["service"] = x["service"].cat.codes
x["flag"] = x["flag"].astype('category')
x["flag"] = x["flag"].cat.codes
y["protocol_type"] = y["protocol_type"].astype('category')
y["protocol_type"] = y["protocol_type"].cat.codes
y["service"] = y["service"].astype('category')
y["service"] = y["service"].cat.codes
y["flag"] = y["flag"].astype('category')
y["flag"] = y["flag"].cat.codes
x_train = x.iloc[: , :26]
y_train = x.iloc[:, 27:]
x_test = y.iloc[: , :26]
y_test = y.iloc[:, 27:]
rfc = RandomForestClassifier(max_depth=2, random_state=0)
rfc.fit(x_train, y_train)
preds = rfc.predict(x_test)
print(f"Train Accuracy: {rfc.score(x_train, y_train)}")
print(f"Test Accuracy: {rfc.score(x_test, y_test)}")
print('Confusion Matrix: \n', confusion_matrix(y_test, preds))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:20: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().


Train Accuracy: 0.9998171116520485
Test Accuracy: 0.998052610429353
Confusion Matrix: 
 [[21424    16     0]
 [  108 19347     0]
 [    0    65 56093]]


In [8]:
x = pd.read_csv('gain_ratio_train.csv')
y = pd.read_csv('gain_ratio_test.csv')
x["protocol_type"] = x["protocol_type"].astype('category')
x["protocol_type"] = x["protocol_type"].cat.codes
x["service"] = x["service"].astype('category')
x["service"] = x["service"].cat.codes
x["flag"] = x["flag"].astype('category')
x["flag"] = x["flag"].cat.codes
y["protocol_type"] = y["protocol_type"].astype('category')
y["protocol_type"] = y["protocol_type"].cat.codes
y["service"] = y["service"].astype('category')
y["service"] = y["service"].cat.codes
y["flag"] = y["flag"].astype('category')
y["flag"] = y["flag"].cat.codes
x_train = x.iloc[: , :25]
y_train = x.iloc[:, 26:]
x_test = y.iloc[: , :25]
y_test = y.iloc[:, 26:]
rfc = RandomForestClassifier(max_depth=2, random_state=5)
rfc.fit(x_train, y_train)
preds = rfc.predict(x_test)
print(f"Train Accuracy: {rfc.score(x_train, y_train)}")
print(f"Test Accuracy: {rfc.score(x_test, y_test)}")
print('Confusion Matrix: \n', confusion_matrix(y_test, preds))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:20: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().


Train Accuracy: 0.9999098437721365
Test Accuracy: 0.9979598775926556
Confusion Matrix: 
 [[21403    37     0]
 [  100 19355     0]
 [    0    61 56097]]


In [7]:
x = pd.read_csv('information_gain_train.csv')
y = pd.read_csv('information_gain_test.csv')
x["protocol_type"] = x["protocol_type"].astype('category')
x["protocol_type"] = x["protocol_type"].cat.codes
x["service"] = x["service"].astype('category')
x["service"] = x["service"].cat.codes
x["flag"] = x["flag"].astype('category')
x["flag"] = x["flag"].cat.codes
y["protocol_type"] = y["protocol_type"].astype('category')
y["protocol_type"] = y["protocol_type"].cat.codes
y["service"] = y["service"].astype('category')
y["service"] = y["service"].cat.codes
y["flag"] = y["flag"].astype('category')
y["flag"] = y["flag"].cat.codes
x_train = x.iloc[: , :26]
y_train = x.iloc[:, 27:]
x_test = y.iloc[: , :26]
y_test = y.iloc[:, 27:]
rfc = RandomForestClassifier(max_depth=2, random_state=10)
rfc.fit(x_train, y_train)
preds = rfc.predict(x_test)
print(f"Train Accuracy: {rfc.score(x_train, y_train)}")
print(f"Test Accuracy: {rfc.score(x_test, y_test)}")
print('Confusion Matrix: \n', confusion_matrix(y_test, preds))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:20: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().


Train Accuracy: 0.9998351428976212
Test Accuracy: 0.9981556469145725
Confusion Matrix: 
 [[21403    37     0]
 [   74 19381     0]
 [    0    68 56090]]
