In [2]:
import sklearn as sk
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.metrics import confusion_matrix
from sklearn.neural_network import MLPClassifier

In [8]:
x = pd.read_csv('cfs_subset_train.csv')
y = pd.read_csv('cfs_subset_test.csv')
x["protocol_type"] = x["protocol_type"].astype('category')
x["protocol_type"] = x["protocol_type"].cat.codes
x["service"] = x["service"].astype('category')
x["service"] = x["service"].cat.codes
x["flag"] = x["flag"].astype('category')
x["flag"] = x["flag"].cat.codes
y["protocol_type"] = y["protocol_type"].astype('category')
y["protocol_type"] = y["protocol_type"].cat.codes
y["service"] = y["service"].astype('category')
y["service"] = y["service"].cat.codes
y["flag"] = y["flag"].astype('category')
y["flag"] = y["flag"].cat.codes
x_train = x.iloc[: , :8]
y_train = x.iloc[:, 9:]
x_test = y.iloc[: , :8]
y_test = y.iloc[:, 9:]
clf = MLPClassifier(random_state=1, max_iter=100).fit(x_train, y_train)
preds = clf.predict(x_test)
print(f"Train Accuracy: {clf.score(x_train, y_train)}")
print(f"Test Accuracy: {clf.score(x_test, y_test)}")
print('Confusion Matrix: \n', confusion_matrix(y_test, preds))

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Train Accuracy: 0.9992632948237445
Test Accuracy: 0.8707304256437205
Confusion Matrix: 
 [[21440     0     0]
 [  890 18565     0]
 [    0 11656 44502]]


In [9]:
x = pd.read_csv('correlation_based_train.csv')
y = pd.read_csv('correlation_based_test.csv')
x["protocol_type"] = x["protocol_type"].astype('category')
x["protocol_type"] = x["protocol_type"].cat.codes
x["service"] = x["service"].astype('category')
x["service"] = x["service"].cat.codes
x["flag"] = x["flag"].astype('category')
x["flag"] = x["flag"].cat.codes
y["protocol_type"] = y["protocol_type"].astype('category')
y["protocol_type"] = y["protocol_type"].cat.codes
y["service"] = y["service"].astype('category')
y["service"] = y["service"].cat.codes
y["flag"] = y["flag"].astype('category')
y["flag"] = y["flag"].cat.codes
x_train = x.iloc[: , :26]
y_train = x.iloc[:, 27:]
x_test = y.iloc[: , :26]
y_test = y.iloc[:, 27:]
clf = MLPClassifier(random_state=1, max_iter=100).fit(x_train, y_train)
preds = clf.predict(x_test)
print(f"Train Accuracy: {clf.score(x_train, y_train)}")
print(f"Test Accuracy: {clf.score(x_test, y_test)}")
print('Confusion Matrix: \n', confusion_matrix(y_test, preds))

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Train Accuracy: 0.9997269554241851
Test Accuracy: 0.4082923763304586
Confusion Matrix: 
 [[21438     2     0]
 [ 1268 18187     0]
 [56129    28     1]]


In [10]:
x = pd.read_csv('gain_ratio_train.csv')
y = pd.read_csv('gain_ratio_test.csv')
x["protocol_type"] = x["protocol_type"].astype('category')
x["protocol_type"] = x["protocol_type"].cat.codes
x["service"] = x["service"].astype('category')
x["service"] = x["service"].cat.codes
x["flag"] = x["flag"].astype('category')
x["flag"] = x["flag"].cat.codes
y["protocol_type"] = y["protocol_type"].astype('category')
y["protocol_type"] = y["protocol_type"].cat.codes
y["service"] = y["service"].astype('category')
y["service"] = y["service"].cat.codes
y["flag"] = y["flag"].astype('category')
y["flag"] = y["flag"].cat.codes
x_train = x.iloc[: , :25]
y_train = x.iloc[:, 26:]
x_test = y.iloc[: , :25]
y_test = y.iloc[:, 26:]
clf = MLPClassifier(random_state=1, max_iter=100).fit(x_train, y_train)
preds = clf.predict(x_test)
print(f"Train Accuracy: {clf.score(x_train, y_train)}")
print(f"Test Accuracy: {clf.score(x_test, y_test)}")
print('Confusion Matrix: \n', confusion_matrix(y_test, preds))

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Train Accuracy: 0.9994436072794715
Test Accuracy: 0.9357361441686501
Confusion Matrix: 
 [[21437     3     0]
 [  216 19239     0]
 [    0  6018 50140]]


In [11]:
x = pd.read_csv('information_gain_train.csv')
y = pd.read_csv('information_gain_test.csv')
x["protocol_type"] = x["protocol_type"].astype('category')
x["protocol_type"] = x["protocol_type"].cat.codes
x["service"] = x["service"].astype('category')
x["service"] = x["service"].cat.codes
x["flag"] = x["flag"].astype('category')
x["flag"] = x["flag"].cat.codes
y["protocol_type"] = y["protocol_type"].astype('category')
y["protocol_type"] = y["protocol_type"].cat.codes
y["service"] = y["service"].astype('category')
y["service"] = y["service"].cat.codes
y["flag"] = y["flag"].astype('category')
y["flag"] = y["flag"].cat.codes
x_train = x.iloc[: , :26]
y_train = x.iloc[:, 27:]
x_test = y.iloc[: , :26]
y_test = y.iloc[:, 27:]
clf = MLPClassifier(random_state=1, max_iter=100).fit(x_train, y_train)
preds = clf.predict(x_test)
print(f"Train Accuracy: {clf.score(x_train, y_train)}")
print(f"Test Accuracy: {clf.score(x_test, y_test)}")
print('Confusion Matrix: \n', confusion_matrix(y_test, preds))

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Train Accuracy: 0.9996522545496697
Test Accuracy: 0.9954766982988676
Confusion Matrix: 
 [[21440     0     0]
 [  406 19045     4]
 [    0    29 56129]]
